blank_issues_enabled: false
contact_links:
  - name: SLRN Scripts
    url: https://discord.gg/TZFBBHvG6E
    about: Ask questions, receive support, and discuss with the community in our Discord server.
