name: "Debug Build Action"

on:
  workflow_dispatch:

jobs:
    debug-build:
        name: "Create Debug Build"
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: ${{ github.event.inputs.branch }}

            - name: Install ZIP
              run: sudo apt install zip

            - name: Install pnpm
              uses: pnpm/action-setup@v4.0.0
              with:
                version: 9

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
                cache: "pnpm"
                cache-dependency-path: "ui/pnpm-lock.yaml"

            - name: Install dependencies
              run: pnpm i --frozen-lockfile
              working-directory: ui

            - name: Run build
              run: pnpm build
              working-directory: ui
              env:
                CI: false

            - name: Bundle files
              run: |
                shopt -s extglob
                mkdir -p ./temp/${{ github.event.repository.name }}
                mkdir -p ./temp/${{ github.event.repository.name }}/ui
                cp ./{README.md,LICENSE,fxmanifest.lua} ./temp/${{ github.event.repository.name }}
                cp -r ./{client,bridge,server} ./temp/${{ github.event.repository.name }}
                cp -r ./ui/dist ./temp/${{ github.event.repository.name }}/ui/
                cd ./temp && zip -r ../${{ github.event.repository.name }}.zip ./${{ github.event.repository.name }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ github.event.repository.name }}
                path: ./temp/
