name: "Discord Release Notification"

on:
    release:
      types: [published]
jobs:
  github-releases-to-discord:
    name: Discord Releases Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Github Releases To Discord
      uses: SethCohen/github-releases-to-discord@v1.15.0
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        color: "16736808"
        username: ${{ github.event.repository.name }}
        avatar_url: "https://slrn.dev/SLRN_Development.png"
        footer_timestamp: true
        footer_title: "SLRN Development"
        footer_icon_url: "https://slrn.dev/SLRN_Development.png"